/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TechStack = {
  _id: string;
  _type: "techStack";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  items: Array<string>;
  order: number;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  body: string;
  publishedAt: string;
  updatedAt?: string;
  tags?: Array<string>;
  source?: "manual" | "assisted" | "automated";
  readTime?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  year: string;
  description: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  technologies: Array<string>;
  demoUrl?: string;
  repositoryUrl?: string;
  caseStudyUrl?: string;
  order: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role: string;
  company: string;
  location?: string;
  period: string;
  summary?: string;
  responsibilities?: RichText;
  technologies?: Array<string>;
  companyUrl?: string;
  order: number;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  email: string;
  githubUrl: string;
  linkedinUrl: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  resume?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  biography: RichText;
  aboutContent: RichText;
  resumeUrl?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type SocialLink = {
  _type: "socialLink";
  label: string;
  url: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TechStack
  | BlogPost
  | Slug
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Experience
  | RichText
  | SanityFileAssetReference
  | Profile
  | SocialLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_id == "profile"][0] {    _id,    name,    role,    email,    githubUrl,    linkedinUrl,    biography,    aboutContent,    photo {      asset->{        _id,        url,        metadata {          lqip,          dimensions { width, height }        }      },      alt,      hotspot,      crop    },    "resumeUrl": resume.asset->url  }
export type PROFILE_QUERY_RESULT =
  | {
      _id: "profile";
      name: string;
      role: string;
      email: string;
      githubUrl: string;
      linkedinUrl: string;
      biography: RichText;
      aboutContent: RichText;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      resumeUrl: string | null;
    }
  | {
      _id: "profile";
      name: null;
      role: null;
      email: null;
      githubUrl: null;
      linkedinUrl: null;
      biography: null;
      aboutContent: null;
      photo: null;
      resumeUrl: null;
    }
  | {
      _id: "profile";
      name: null;
      role: string;
      email: null;
      githubUrl: null;
      linkedinUrl: null;
      biography: null;
      aboutContent: null;
      photo: null;
      resumeUrl: null;
    }
  | {
      _id: "profile";
      name: string;
      role: null;
      email: null;
      githubUrl: null;
      linkedinUrl: null;
      biography: null;
      aboutContent: null;
      photo: null;
      resumeUrl: null;
    }
  | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(order desc, _id asc) {    _id,    role,    company,    period,    technologies  }
export type EXPERIENCE_QUERY_RESULT = Array<{
  _id: string;
  role: string;
  company: string;
  period: string;
  technologies: Array<string> | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order desc, _id asc) {    _id,    title,    year,    description,    image {      asset->{        _id,        url,        metadata {          lqip,          dimensions { width, height }        }      },      alt,      hotspot,      crop    },    technologies,    demoUrl,    repositoryUrl,    caseStudyUrl  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  year: string;
  description: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  technologies: Array<string>;
  demoUrl: string | null;
  repositoryUrl: string | null;
  caseStudyUrl: string | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current) && defined(publishedAt)]  | order(publishedAt desc, _id asc) {    _id,    title,    "slug": slug.current,    "date": publishedAt,    "description": excerpt,    tags  }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  date: string;
  description: string;
  tags: Array<string> | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: BLOG_POST_QUERY
// Query: *[_type == "blogPost" && slug.current == $slug && defined(publishedAt)][0] {    _id,    title,    "slug": slug.current,    "date": publishedAt,    "description": excerpt,    tags,    body,    readTime  }
export type BLOG_POST_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  date: string;
  description: string;
  tags: Array<string> | null;
  body: string;
  readTime: number | null;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: BLOG_POST_SLUGS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current) && defined(publishedAt)] | order(_id asc) {    "slug": slug.current  }
export type BLOG_POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: TECH_STACK_QUERY
// Query: *[_type == "techStack"] | order(order asc, _id asc) {    _id,    name,    items,    order  }
export type TECH_STACK_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  items: Array<string>;
  order: number;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "profile"][0] {\n    _id,\n    name,\n    role,\n    email,\n    githubUrl,\n    linkedinUrl,\n    biography,\n    aboutContent,\n    photo {\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions { width, height }\n        }\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    "resumeUrl": resume.asset->url\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "experience"] | order(order desc, _id asc) {\n    _id,\n    role,\n    company,\n    period,\n    technologies\n  }\n': EXPERIENCE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order desc, _id asc) {\n    _id,\n    title,\n    year,\n    description,\n    image {\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions { width, height }\n        }\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    technologies,\n    demoUrl,\n    repositoryUrl,\n    caseStudyUrl\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "blogPost" && defined(slug.current) && defined(publishedAt)]\n  | order(publishedAt desc, _id asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    "date": publishedAt,\n    "description": excerpt,\n    tags\n  }\n': BLOG_POSTS_QUERY_RESULT;
    '\n  *[_type == "blogPost" && slug.current == $slug && defined(publishedAt)][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    "date": publishedAt,\n    "description": excerpt,\n    tags,\n    body,\n    readTime\n  }\n': BLOG_POST_QUERY_RESULT;
    '\n  *[_type == "blogPost" && defined(slug.current) && defined(publishedAt)] | order(_id asc) {\n    "slug": slug.current\n  }\n': BLOG_POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "techStack"] | order(order asc, _id asc) {\n    _id,\n    name,\n    items,\n    order\n  }\n': TECH_STACK_QUERY_RESULT;
  }
}
